# Generated by Django 3.2.9 on 2021-12-30 09:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardsAndAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('received', models.DateField()),
            ],
            options={
                'verbose_name': 'Award and Achievement Entry',
                'verbose_name_plural': 'Award and Achievement Entries',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Experience Entry',
                'verbose_name_plural': 'Experience Entries',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('gisturl', models.URLField(max_length=255)),
            ],
            options={
                'verbose_name': 'Note Entry',
                'verbose_name_plural': 'Note Entries',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, max_length=1000)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('category', models.CharField(choices=[('Web Apps', 'Web Apps'), ('Machine Learning', 'Machine Learning'), ('APIs', 'APIs'), ('Command Line Applications', 'Command Line Applications'), ('Data Visualization', 'Data Visualization'), ('Graphical User Interfaces', 'Graphical User Interfaces'), ('Artificial Intelligence', 'Artificial Intelligence'), ('DevOps', 'DevOps'), ('Data Science', 'Data Science'), ('Other', 'Other')], default='Other', max_length=50)),
                ('urllink', models.URLField(max_length=255)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField(blank=True, null=True)),
                ('technology', models.CharField(max_length=255)),
                ('sourcecode', models.URLField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('publish', models.BooleanField(default=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project Entry',
                'verbose_name_plural': 'Project Entries',
                'ordering': ['category', '-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Summary Entry',
                'verbose_name_plural': 'Summary Entries',
            },
        ),
    ]
