# Generated by Django 3.2.9 on 2022-01-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
