# Generated by Django 3.2.9 on 2022-01-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_notes_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='summary_image',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
