# Generated by Django 3.2.9 on 2022-01-23 04:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_projects_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='title',
            field=models.CharField(default=datetime.datetime(2022, 1, 23, 4, 41, 35, 451124, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
